vich_uploader:
    db_driver: orm
    mappings:
        user_image: 
            uri_prefix: /uploads/user_images
            upload_destination: '%kernel.project_dir%/public/uploads/user_images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
